import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const port = Number(process.env.ARTEL_WORK_QA_PORT || 5192), base = `http://127.0.0.1:${port}`;
const output = resolve(root, 'qa/workspace-work');
await mkdir(output, { recursive: true });
const temporary = await mkdtemp(resolve(tmpdir(), 'artel-work-browser-'));
const live = resolve(root, 'data/local-operations/operations.json');
const checksum = async () => existsSync(live) ? createHash('sha256').update(await readFile(live)).digest('hex') : null;
const before = await checksum();
const report = { checks: [], screenshots: [], errors: [], measurements: [], temporaryStoreRemoved: false, liveStoreUnchanged: false, serverMode: 'vite dev' };
const check = name => { report.checks.push(name); console.log('PASS', name); };
let server, browser;
try {
  await assert.rejects(fetch(base, { signal: AbortSignal.timeout(500) }), 'QA port must be unused');
  server = spawn(process.execPath, [resolve(root, 'node_modules/vite/bin/vite.js'), '--host', '127.0.0.1', '--port', String(port), '--strictPort'], { cwd: root, env: { ...process.env, ARTEL_STORE_DIR: temporary, CHECKO_API_KEY: '' }, stdio: 'ignore' });
  for (let retry = 0; retry < 100; retry++) { try { if ((await fetch(`${base}/api/auth/session`)).ok) break; } catch {} await new Promise(done => setTimeout(done, 100)); }
  const password = randomUUID();
  const setup = await fetch(`${base}/api/auth/setup`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ login: 'work-qa-director', name: 'Директор QA', password }) });
  assert.equal(setup.status, 200);
  const directorCookie = setup.headers.get('set-cookie').split(';')[0];
  const api = async (path, method = 'GET', data) => { const response = await fetch(base + path, { method, headers: { Cookie: directorCookie, ...(data ? { 'Content-Type': 'application/json' } : {}) }, ...(data ? { body: JSON.stringify(data) } : {}) }); const body = await response.json(); assert.ok(response.ok, JSON.stringify(body)); return body; };
  const alice = (await api('/api/auth/users', 'POST', { name: 'Анна QA', login: 'work-qa-alice', password, role: 'manager', managerId: null })).user;
  const bob = (await api('/api/auth/users', 'POST', { name: 'Борис QA', login: 'work-qa-bob', password, role: 'manager', managerId: null })).user;
  const companies = (await api('/api/snapshot')).companies;
  browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  const context = async user => { const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', timezoneId: 'Europe/Moscow' }); assert.equal((await context.request.post(`${base}/api/auth/login`, { data: { login: user.login, password } })).status(), 200); const page = await context.newPage(); page.on('pageerror', error => report.errors.push(error.message)); await page.goto(`${base}/#work`); await expect(page.getByRole('button', { name: 'Новая задача', exact: true })).toBeEnabled(); return { context, page }; };
  const first = await context(alice), second = await context(bob), a = first.page, b = second.page;
  const openEditor = page => page.getByRole('dialog');
  await a.getByRole('button', { name: 'Новая задача', exact: true }).click();
  let editor = openEditor(a);
  await editor.getByLabel('Название', { exact: true }).fill('Согласовать поставку QA');
  await editor.getByLabel('Описание', { exact: true }).fill('Уточнить документы и срок доставки.');
  await editor.getByLabel('Новый комментарий', { exact: true }).fill('Комментарий к задаче');
  await editor.getByLabel('Прикрепить файлы').setInputFiles({ name: 'договор-QA.txt', mimeType: 'text/plain', buffer: Buffer.from('Проверенный файл для коллеги') });
  await editor.getByRole('combobox', { name: /^Компания/ }).fill(companies[0].name);
  await editor.getByRole('option').first().click();
  const today = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Europe/Moscow' }).format(new Date());
  await editor.getByLabel('Срок задачи', { exact: true }).fill(today);
  await editor.getByLabel('Напоминание', { exact: true }).fill(`${today}T12:30`);
  await editor.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(a.getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true })).toBeVisible();
  await b.getByRole('button', { name: 'Обновить работу' }).click();
  await expect(b.getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true })).toHaveCount(0);
  await a.getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true }).click();
  editor = openEditor(a);
  await editor.getByLabel('Исполнитель', { exact: true }).selectOption(bob.id);
  await editor.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(a.getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true })).toHaveCount(0);
  await b.getByRole('button', { name: 'Обновить работу' }).click();
  await expect(b.getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true })).toBeVisible();
  check('Two distinct browser accounts: task created for A, hidden from B, handed A→B, removed from A and visible to B');
  await b.getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true }).click();
  editor = openEditor(b); await expect(editor.locator('.work-comments article')).toHaveCount(1);
  const downloaded = b.waitForEvent('download'); await editor.getByRole('link', { name: /договор-QA.txt/ }).click();
  assert.equal(await readFile(await (await downloaded).path(), 'utf8'), 'Проверенный файл для коллеги');
  await editor.getByLabel('Название', {exact:true}).fill('Согласовать поставку QA');
  await editor.getByLabel('Новый комментарий', {exact:true}).fill('Файл получен');
  await editor.getByLabel('Состояние задачи').selectOption('doing');
  check('Assignee downloads original file bytes and sees task comments');
  await editor.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(b.locator('.work-company-list').getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true })).toBeVisible();
  await b.getByRole('button', { name: 'Календарь', exact: true }).click();
  await expect(b.locator('.work-calendar-event')).toHaveCount(2);
  await b.locator('.work-calendar-event').first().click();
  await expect(openEditor(b).getByLabel('Напоминание', { exact: true })).toHaveValue(`${today}T12:30`);
  await openEditor(b).getByRole('button', { name: 'Отмена', exact: true }).click();
  const calendarPath = resolve(output, 'calendar-1440.png'); await b.screenshot({ path: calendarPath, fullPage: true }); report.screenshots.push(calendarPath);
  check('Task state change, due date and local-time reminder round-trip through calendar');
  await b.getByRole('button', { name: 'Работа с компаниями', exact: true }).click();
  await b.getByLabel('Поиск компании в работе').fill('несуществующая компания');
  await expect(b.locator('.work-card')).toHaveCount(0);
  await b.getByLabel('Поиск компании в работе').fill(companies[0].name);
  await expect(b.locator('.work-card')).toHaveCount(1);
  await b.getByLabel('Поиск компании в работе').fill('');
  check('Unified company search hides nonmatches and finds the linked task');
  await b.locator('.work-companies').getByRole('button', { name: 'Добавить', exact: true }).click();
  editor = openEditor(b); await editor.getByRole('combobox', { name: /^Компания/ }).fill(companies[0].name);
  await editor.getByRole('option').first().click();
  await editor.getByLabel('Текущий вопрос', { exact: true }).fill('Нужна копия договора QA');
  await editor.getByLabel('Новый комментарий', { exact: true }).fill('Запрос отправлен сотруднику.');
  await editor.getByLabel('Напоминание', { exact: true }).fill(`${today}T15:00`);
  await editor.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(b.locator('.work-company-row')).toHaveCount(1);
  await b.locator('.work-company-row').click(); editor = openEditor(b);
  await expect(editor.locator('.work-comments article')).toHaveCount(1);
  await editor.getByLabel('Новый комментарий', { exact: true }).fill('Документ получен.');
  await editor.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await b.reload(); await expect(b.locator('.work-company-row')).toHaveCount(1);
  await b.locator('.work-company-row').click(); editor = openEditor(b);
  await expect(editor.locator('.work-comments article')).toHaveCount(2);
  await editor.getByRole('button', { name: 'Отмена', exact: true }).click();
  check('Company question, two authored comments and reminder persist after reload');
  await a.getByRole('button', { name: 'Добавить заметку' }).click(); editor = openEditor(a);
  await editor.getByLabel('Название', { exact: true }).fill('Документы QA');
  await editor.getByLabel('Текст заметки', { exact: true }).fill('Сверить реквизиты перед встречей.');
  await editor.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await a.reload(); await expect(a.getByRole('button', { name: 'Заметка: Документы QA', exact: true })).toBeVisible();
  await b.getByRole('button', { name: 'Обновить работу' }).click(); await expect(b.getByRole('button', { name: 'Заметка: Документы QA', exact: true })).toHaveCount(0);
  assert.equal((await api('/api/work')).work.notes.length, 1);
  check('Separate persisted note belongs to A, is hidden from B, and is visible to director');
  for (const width of [1440, 1024, 768, 390, 320]) {
    await b.setViewportSize({ width, height: 1000 });
    const measurement = await b.evaluate(() => ({ width: innerWidth, documentWidth: document.documentElement.scrollWidth, workspaceWidth: document.querySelector('.work-page').getBoundingClientRect().width }));
    assert.ok(measurement.documentWidth <= width + 1, JSON.stringify(measurement)); report.measurements.push(measurement);
    const path = resolve(output, `board-${width}.png`); await b.screenshot({ path, fullPage: true }); report.screenshots.push(path);
  }
  check('Unified list, company records and reminders fit desktop, tablet and 320/390px mobile viewports');
  await b.getByRole('button', { name: 'Задача: Согласовать поставку QA', exact: true }).click(); editor = openEditor(b);
  const formPath = resolve(output, 'editor-320.png'); await b.screenshot({ path: formPath, fullPage: true }); report.screenshots.push(formPath);
  await editor.getByRole('button', { name: 'В архив задач', exact: true }).click();
  await editor.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(b.locator('.work-card')).toHaveCount(0);
  await b.getByRole('button', { name: 'Архив задач', exact: true }).click();
  await expect(b.locator('.work-card')).toHaveCount(1);
  await b.locator('.work-card').click(); editor = openEditor(b);
  await expect(editor.locator('.work-comments article')).toHaveCount(2);
  await expect(editor.getByRole('link', { name: /договор-QA.txt/ })).toBeVisible();
  await editor.getByRole('button', { name: 'Отмена', exact: true }).click();
  await b.reload(); await b.getByRole('button', {name:'Архив задач',exact:true}).click();
  await expect(b.locator('.work-card')).toHaveCount(1);
  const archived=(await api('/api/work')).work.tasks[0]; assert.ok(archived.archivedAt); assert.equal(archived.comments.length,2); assert.equal(archived.attachments.length,1);
  check('Archive persists after reload and retains task, company, assignee, dates, two comments and attachment');
  assert.deepEqual(report.errors, []); check('No browser JavaScript errors');
} finally {
  await browser?.close();
  if (server && server.exitCode === null) { server.kill('SIGTERM'); await new Promise(done => { server.once('exit', done); setTimeout(done, 5000); }); }
  await rm(temporary, { recursive: true, force: true }); report.temporaryStoreRemoved = !existsSync(temporary);
  report.liveStoreUnchanged = before === await checksum();
  await writeFile(resolve(output, 'report.json'), JSON.stringify(report, null, 2));
  assert.ok(report.liveStoreUnchanged, 'Live operations store must be unchanged');
}
