import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { loadSnapshot } from '../server/local-api.ts';
import { OperationsStore, decodeOperations } from '../server/operations-store.ts';
import { clearOperations } from '../server/reset-operations.ts';
const root=resolve(import.meta.dirname,'..'), port=5196, base=`http://127.0.0.1:${port}`, output=resolve(root,'qa/requirements-2026-09-10');
await mkdir(output,{recursive:true});
const temporary=await mkdtemp(resolve(tmpdir(),'artel-requirements-ui-')),live=resolve(root,'data/local-operations/operations.json');
const checksum=async()=>existsSync(live)?createHash('sha256').update(await readFile(live)).digest('hex'):null;
const before=await checksum(), source=await loadSnapshot(resolve(root,'data/local-xlsx-final')), store=new OperationsStore(temporary);
await store.mutate(source.provenance.sourceSha256,data=>({result:clearOperations(source,data),changed:true}));
const report={checks:[],screenshots:[],errors:[],liveStoreUnchanged:false,status:'running'};const check=name=>{report.checks.push(name);console.log('PASS',name)};
let server,browser,page;
try {
  await assert.rejects(fetch(base,{signal:AbortSignal.timeout(500)}),'QA port must be unused');
  server=spawn(process.execPath,[resolve(root,'node_modules/vite/bin/vite.js'),'preview','--host','127.0.0.1','--port',String(port),'--strictPort'],{cwd:root,env:{...process.env,ARTEL_STORE_DIR:temporary,CHECKO_API_KEY:''},stdio:'ignore'});
  let ready=false;for(let count=0;count<100;count++){try{if((await fetch(base+'/api/auth/session')).ok){ready=true;break}}catch{}await new Promise(done=>setTimeout(done,100))}assert.ok(ready);
  const password=randomUUID(),setup=await fetch(base+'/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:'requirements-director',name:'Директор QA',password})});assert.equal(setup.status,200);const cookie=setup.headers.get('set-cookie').split(';')[0];
  const api=async(path,method='GET',body)=>{const response=await fetch(base+path,{method,headers:{Cookie:cookie,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const value=await response.json();assert.ok(response.ok,JSON.stringify(value));return value};
  const originalForms=(await api('/api/snapshot')).directories.paymentForms;
  browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',timezoneId:'Europe/Moscow'});
  await context.addCookies([{name:cookie.slice(0,cookie.indexOf('=')),value:cookie.slice(cookie.indexOf('=')+1),url:base,httpOnly:true,sameSite:'Lax'}]);
  page=await context.newPage();page.on('pageerror',error=>report.errors.push(error.message));
  const screenshot=async(name,p=page)=>{const path=resolve(output,name+'.png');await p.screenshot({path,fullPage:true});report.screenshots.push(path)};
  const choose=async(scope,label,name)=>{const input=scope.getByRole('combobox',{name:new RegExp(`^${label}`)});await input.click();await input.fill(name);await scope.getByRole('option').first().click();await expect(input).toHaveValue(name)};
  await page.goto(base+'/#directories');
  for(const name of ['Формы оплаты','Форма оплаты','Адреса','Клиенты и менеджеры'])await expect(page.getByRole('group',{name:'Справочники',exact:true}).getByRole('button',{name,exact:true})).toHaveCount(0);
  const initialStore=await readFile(store.path,'utf8');
  await page.getByRole('button',{name:'Очистка справочников',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Создать копию и очистить',exact:true})).toBeEnabled();await screenshot('cleanup-preview');
  await dialog.getByRole('button',{name:'Создать копию и очистить',exact:true}).click();await expect(dialog).toHaveCount(0,{timeout:20000});
  const snapshot=await api('/api/snapshot');assert.deepEqual(snapshot.directories.paymentForms,originalForms);assert.equal(originalForms.length,3);assert.equal(snapshot.directories.managers.length,0);assert.equal(snapshot.companies.filter(c=>c.roles.some(r=>['customer','supplier'].includes(r))).length,0);
  const backupText=await page.getByRole('status').innerText(),backupPath=backupText.slice(backupText.indexOf('копия: ')+7).trim();assert.deepEqual(decodeOperations(await readFile(backupPath,'utf8'),source.provenance.sourceSha256),decodeOperations(initialStore,source.provenance.sourceSha256));
  await page.reload();await expect(page.getByText('Записей: 0',{exact:true})).toBeVisible();check('Removed directory tabs; explicit cleanup on temporary data, verified prior backup, forms/accounts preserved and no source reimport');
  const manager=(await api('/api/directories','POST',{kind:'managers',name:'Нуры QA'})).entry;
  const product=(await api('/api/directories','POST',{kind:'products',name:'Дизель QA'})).entry;
  await page.reload();await page.getByRole('button',{name:'Добавить',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Наименование',{exact:true}).fill('СПС QA');await choose(dialog,'Менеджер компании',manager.name);
  await dialog.locator('.company-address-group').filter({hasText:'Фактические адреса отгрузки'}).getByRole('button',{name:'Добавить адрес',exact:true}).click();
  await dialog.getByLabel('Адрес отгрузки клиента 1',{exact:true}).fill('Фактический адрес клиента QA');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);
  const customer=(await api('/api/snapshot')).companies.find(c=>c.name==='СПС QA');assert.ok(customer);
  await page.getByRole('button',{name:'Редактировать: СПС QA',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Адрес отгрузки клиента 1',{exact:true})).toHaveValue('Фактический адрес клиента QA');await dialog.getByLabel('Адрес отгрузки клиента 1',{exact:true}).fill('Новый адрес клиента QA');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);
  await page.getByRole('button',{name:'Поставщики',exact:true}).click();await page.getByRole('button',{name:'Добавить',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Наименование',{exact:true}).fill('Поставщик Китай QA');await dialog.getByRole('button',{name:'Добавить адрес',exact:true}).click();await dialog.getByLabel('Адрес загрузки 1',{exact:true}).fill('Фактический адрес загрузки QA');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);
  await page.getByRole('button',{name:'Редактировать: Поставщик Китай QA',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Адрес загрузки 1',{exact:true})).toHaveValue('Фактический адрес загрузки QA');await dialog.getByLabel('Адрес загрузки 1',{exact:true}).fill('Новый адрес загрузки QA');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);
  const edited=await api('/api/snapshot');assert.ok(edited.directories.addresses.some(a=>a.name==='Новый адрес клиента QA'&&a.companyId===customer.id));assert.ok(edited.directories.addresses.some(a=>a.name==='Новый адрес загрузки QA'));
  check('Client and supplier cards add/read/edit factual addresses; client manager relation saved before user setup');
  const supplier=edited.companies.find(c=>c.name==='Поставщик Китай QA');const secondSupplier=(await api('/api/directories','POST',{kind:'companies',name:'Второй поставщик QA',roles:['supplier'],addresses:[]})).entry;
  const user=(await api('/api/auth/users','POST',{name:'Нуры QA',login:'requirements-manager',password,role:'manager',managerId:manager.id})).user;
  const managerContext=await browser.newContext({viewport:{width:1440,height:1000}});assert.equal((await managerContext.request.post(base+'/api/auth/login',{data:{login:user.login,password}})).status(),200);const managerPage=await managerContext.newPage();managerPage.on('pageerror',e=>report.errors.push(e.message));await managerPage.goto(base+'/#shipments');await managerPage.getByRole('tab',{name:'АЗС',exact:true}).click();await managerPage.getByRole('button',{name:'Добавить отгрузку',exact:true}).click();dialog=managerPage.getByRole('dialog');await choose(dialog,'Контрагент',customer.name);await expect(dialog.getByRole('combobox',{name:/^Менеджер/})).toHaveValue(manager.name);await choose(dialog,'Поставщик',supplier.name);await choose(dialog,'Товар',product.name);await choose(dialog,'Форма оплаты','б/нал');await dialog.getByLabel('Количество литров',{exact:true}).fill('100');await dialog.getByLabel('Сумма покупателя, ₽',{exact:true}).fill('1000');await dialog.getByLabel('Сумма поставщика, ₽',{exact:true}).fill('800');await dialog.getByRole('button',{name:'Сохранить отгрузку',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(managerPage.getByTestId('shipments-loaded-count')).toHaveAttribute('data-total','1');await screenshot('manager-assigned-client',managerPage);check('New manager account automatically gets previously assigned СПС client, manager autofills and shipment saves under that account');
  await page.goto(base+'/#china');await expect(page.getByText('Баланс: расчёт не настроен',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Добавить день',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Дата',{exact:true}).fill('2026-09-10');await choose(dialog,'Поставщик 1',supplier.name);await dialog.getByLabel('Количество литров 1',{exact:true}).fill('100.1');await dialog.getByLabel('Сумма 1',{exact:true}).fill('200.25');await dialog.getByRole('button',{name:'Добавить поставщика',exact:true}).click();await choose(dialog,'Поставщик 2',secondSupplier.name);await dialog.getByLabel('Количество литров 2',{exact:true}).fill('300.2');await dialog.getByLabel('Сумма 2',{exact:true}).fill('500.75');await screenshot('china-day-editor');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('.china-table tbody tr')).toHaveCount(1);let row=page.locator('.china-table tbody tr');await expect(row.locator('td').nth(1)).toHaveText('400,3');await expect(row.locator('td').nth(2).locator('strong')).toHaveText('701');
  await page.getByRole('button',{name:'Добавить платёж',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Дата',{exact:true}).fill('2026-09-10');await dialog.getByLabel('Сумма платежа',{exact:true}).fill('900.35');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(row.locator('td').nth(3).locator('strong')).toHaveText('+900,35');
  await page.getByRole('button',{name:'Добавить платёж',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Дата',{exact:true}).fill('2026-09-11');await dialog.getByLabel('Сумма платежа',{exact:true}).fill('50');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);await page.reload();await expect(page.locator('.china-table tbody tr')).toHaveCount(2);await page.getByRole('button',{name:'Открыть день 2026-09-10',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:/^Поставщик/})).toHaveCount(2);await expect(dialog.getByLabel('Количество литров 2',{exact:true})).toHaveValue('300.2');await dialog.getByLabel('Количество литров 2',{exact:true}).fill('301.2');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);const china=(await api('/api/china')).china;assert.equal(china.days[0].fuels[1].litres,'301.2');assert.equal(china.payments.length,2);assert.ok(!('balance' in china));check('China multiple suppliers, exact day totals, separate + payments on same and payment-only dates, reload and day edit; no numeric balance');
  for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await screenshot(`china-${width}`)}
  await page.getByRole('button',{name:'Открыть день 2026-09-10',exact:true}).click();dialog=page.getByRole('dialog');assert.ok(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await screenshot('china-editor-320');await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
  await page.goto(base+'/#directories');await page.getByRole('button',{name:'Очистка справочников',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('alert')).toContainText('используется');await expect(dialog.getByRole('button',{name:'Создать копию и очистить',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Отмена',exact:true}).click();assert.equal((await api('/api/china')).china.days.length,1);check('Responsive China table/forms and cleanup blocks linked records without deleting documents');
  await page.goto(base+'/#operator');await expect(page.getByText(/Excel-файл с системой учёта не предоставлен/)).toBeVisible();for(const route of ['overview','stock']){await page.goto(base+'/#'+route);await expect(page.locator('.blank-workspace')).toBeEmpty()}
  await page.goto(base+'/#payroll');await expect(page.getByRole('tab',{name:/водител/})).toBeVisible();await expect(page.getByRole('tab',{name:/менеджер/})).toBeVisible();check('Operator limitation shown; overview/stock remain empty and payroll switch retained');
  assert.deepEqual(report.errors,[]);report.status='passed';
}catch(error){report.status='failed';report.error=String(error.stack||error);if(page)await screenshotFallback();throw error}
finally{await browser?.close();if(server){server.kill('SIGTERM');await new Promise(done=>{server.once('exit',done);setTimeout(done,5000)})}report.liveStoreUnchanged=before===await checksum();await rm(temporary,{recursive:true,force:true});await writeFile(resolve(output,'verification.json'),JSON.stringify(report,null,2));assert.ok(report.liveStoreUnchanged)}
async function screenshotFallback(){await page.screenshot({path:resolve(output,'failure.png'),fullPage:true}).catch(()=>{})}
