import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { chromium, expect } from '@playwright/test';
import { startTripsQaServer, writeTripsQaSnapshot } from './qa-trips-runtime.mjs';
import { authenticateContext, bootstrapQaAuth } from './qa-auth.mjs';

const root=resolve(import.meta.dirname,'..'),directory=await mkdtemp(resolve(tmpdir(),'artel-directory-transport-ui-'));
const snapshotDirectory=resolve(directory,'snapshot'),operationsDirectory=resolve(directory,'operations');
await writeTripsQaSnapshot(snapshotDirectory);
let runtime,browser;
try {
  runtime=await startTripsQaServer({root,snapshotDirectory,operationsDirectory});
  const auth=await bootstrapQaAuth(runtime.base);
  browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const page=await browser.newPage({viewport:{width:1280,height:960}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await authenticateContext(page.context(),runtime.base,auth.cookie);
  await page.goto(runtime.base+'/#directories');
  const tabs=page.getByRole('group',{name:'Справочники',exact:true});
  for(const name of ['Компании','Перевозчики'])await expect(tabs.getByRole('button',{name,exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Очистка справочников',exact:true})).toHaveCount(0);
  await expect(tabs.getByRole('button')).toHaveCount(8);
  console.log('PASS eight directory tabs; no global companies, carriers or cleanup control');
  const tab=async name=>page.getByRole('group',{name:'Справочники',exact:true}).getByRole('button',{name,exact:true}).click();
  const add=async()=>{await page.getByRole('button',{name:'Добавить',exact:true}).click();return page.getByRole('dialog');};
  const save=async dialog=>{await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);};
  const edit=async name=>{await page.getByRole('button',{name:`Редактировать: ${name}`,exact:true}).click();return page.getByRole('dialog');};
  const choose=async(dialog,label,name)=>{const picker=dialog.getByRole('combobox',{name:label,exact:true});await picker.fill(name);await dialog.getByRole('option',{name,exact:true}).click();await expect(picker).toHaveValue(name);};
  const request=async(path,method='GET',body)=>{const response=await fetch(runtime.base+path,{method,headers:{cookie:auth.cookie,origin:runtime.base,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,body:await response.json()};};
  await tab('Товары');let dialog=await add();
  await dialog.getByLabel('Название товара',{exact:true}).fill('QA ДТ');
  await dialog.getByLabel('Полное наименование для документов',{exact:true}).fill('Дизельный продукт для синтетического теста');
  await dialog.getByLabel('Автоматизация транспортных документов',{exact:true}).selectOption('diesel');
  await dialog.getByLabel('Способ перевозки груза',{exact:true}).selectOption('bulk');
  await dialog.getByLabel('Номер ООН',{exact:true}).fill('0000');
  await dialog.getByLabel('Источник характеристик опасного груза',{exact:true}).fill('Тестовый справочник');
  await save(dialog);dialog=await edit('QA ДТ');
  await expect(dialog.getByLabel('Полное наименование для документов',{exact:true})).toHaveValue('Дизельный продукт для синтетического теста');
  await expect(dialog.getByLabel('Номер ООН',{exact:true})).toHaveValue('0000');
  await expect(dialog.getByLabel('Способ перевозки груза',{exact:true})).toHaveValue('bulk');
  await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
  console.log('PASS product profile save and reopen without inferred dangerous characteristics');

  await tab('Автомобили');dialog=await add();
  await dialog.getByLabel('Автомобиль / номер',{exact:true}).fill('QA машина 991');
  await dialog.getByLabel('Подтверждённая грузоподъёмность, т',{exact:true}).fill('8,5');
  await dialog.getByLabel('Основание владения',{exact:true}).selectOption('3');
  await dialog.getByLabel('Наименование договора',{exact:true}).fill('Синтетическая аренда');
  await dialog.getByLabel('Номер договора',{exact:true}).fill('QA-01');
  await dialog.getByLabel('Дата договора',{exact:true}).fill('30.09.2026');
  await expect(dialog.getByLabel('Распределение груза по платформе',{exact:true})).toHaveValue('');
  await dialog.getByLabel('Распределение груза по платформе',{exact:true}).selectOption('0');
  await save(dialog);
  await page.getByLabel('Поиск в справочнике',{exact:true}).fill('QA машина');
  dialog=await edit('QA машина 991');
  await expect(dialog.getByLabel('Подтверждённая грузоподъёмность, т',{exact:true})).toHaveValue('8.5');
  await expect(dialog.getByLabel('Дата договора',{exact:true})).toHaveValue('2026-09-30');
  await expect(dialog.getByLabel('Распределение груза по платформе',{exact:true})).toHaveValue('0');
  await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
  const vehicle=(await request('/api/snapshot')).body.directories.vehicles.find(row=>row.plate==='QA машина 991');
  assert.equal((await request(`/api/directories/vehicles/${vehicle.id}`,'PATCH',{version:vehicle.version??0,plate:vehicle.plate,cargoDistributable:'2'})).status,400);
  console.log('PASS vehicle payload, lease and cargo distribution save/reopen; invalid choice rejected');

  await tab('Клиенты');dialog=await add();
  await dialog.getByLabel('Наименование',{exact:true}).fill('QA получатель');
  await dialog.locator('.company-address-group').getByRole('button',{name:'Добавить адрес'}).click();
  await dialog.getByLabel('Адрес отгрузки клиента 1',{exact:true}).fill('QA площадка');
  await dialog.getByLabel('Приёмщик адреса 1',{exact:true}).fill('Тестовый Приёмщик');
  await dialog.getByLabel('Телефон приёмщика адреса 1',{exact:true}).fill('+7 (900) 000-00-00');
  await save(dialog);
  await tab('Места погрузки и доставки');dialog=await edit('QA площадка');
  await expect(dialog.getByLabel('Приёмщик',{exact:true})).toHaveValue('Тестовый Приёмщик');
  await dialog.getByLabel('Телефон приёмщика',{exact:true}).fill('+7 (900) 000-00-01');
  await save(dialog);
  await page.reload();await tab('Клиенты');dialog=await edit('QA получатель');
  await expect(dialog.getByLabel('Телефон приёмщика адреса 1',{exact:true})).toHaveValue('+7 (900) 000-00-01');
  await page.setViewportSize({width:390,height:844});
  assert.ok(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth+1),'Company form overflows on mobile');
  await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
  console.log('PASS address contact round-trip between client and address forms, mobile fit');
  await page.setViewportSize({width:1280,height:960});
  await tab('Поставщики');dialog=await add();
  await dialog.getByLabel('Наименование',{exact:true}).fill('QA компания погрузки');
  await expect(dialog.getByRole('button',{name:'Добавить адрес',exact:true})).toHaveCount(0);
  await dialog.getByLabel('Юридический адрес',{exact:true}).fill('QA юридический адрес, 9');await save(dialog);
  const beforeParties=(await request('/api/snapshot')).body;
  const actorBefore=beforeParties.companies.find(row=>row.name==='QA получатель');
  const actorAddresses=beforeParties.directories.addresses.filter(row=>row.companyId===actorBefore.id);
  const supplierBefore=beforeParties.companies.find(row=>row.name==='QA компания погрузки');
  await tab('Нефтебазы');await add();dialog=page.getByRole('dialog',{name:'Добавление нефтебазы',exact:true});
  await dialog.getByLabel('Наименование нефтебазы',{exact:true}).fill('QA нефтебаза');
  await dialog.getByLabel('Фактический адрес места погрузки / пункта подачи',{exact:true}).fill('QA фактический адрес, 1');
  await choose(dialog,'Лицо, осуществляющее погрузку','QA получатель');
  await choose(dialog,'Владелец инфраструктуры погрузки','QA компания погрузки');
  await page.setViewportSize({width:390,height:844});
  const ownerPicker=dialog.getByRole('combobox',{name:'Компания — владелец нефтебазы',exact:true});
  await ownerPicker.click();await expect(dialog.getByRole('option')).toHaveCount(0);
  await expect(dialog.getByRole('listbox')).toContainText('Введите наименование или ИНН');
  await ownerPicker.press('Escape');
  assert.ok(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth+1),'Loading role selectors overflow on mobile');
  await dialog.getByRole('button',{name:'Добавить организацию: Компания — владелец нефтебазы',exact:true}).click();
  let party=page.getByRole('dialog',{name:'Добавление участника погрузки',exact:true});
  await expect(party.getByRole('checkbox')).toHaveCount(0);
  await party.getByLabel('Наименование',{exact:true}).fill('QA отдельный владелец');
  await party.getByLabel('ИНН',{exact:true}).fill('7707083893');
  await party.getByLabel('Юридический адрес',{exact:true}).fill('QA юридический адрес владельца, 2');
  assert.ok(await party.evaluate(element=>element.scrollWidth<=element.clientWidth+1),'Contextual participant editor overflows on mobile');
  await save(party);
  await expect(dialog).toBeVisible();
  await expect(dialog.getByLabel('Наименование нефтебазы',{exact:true})).toHaveValue('QA нефтебаза');
  await expect(dialog.getByLabel('Фактический адрес места погрузки / пункта подачи',{exact:true})).toHaveValue('QA фактический адрес, 1');
  await expect(ownerPicker).toHaveValue('QA отдельный владелец');
  await expect(dialog.getByRole('combobox',{name:'Лицо, осуществляющее погрузку',exact:true})).toHaveValue('QA получатель');
  await expect(dialog.getByRole('combobox',{name:'Владелец инфраструктуры погрузки',exact:true})).toHaveValue('QA компания погрузки');
  await expect(dialog).toContainText('QA юридический адрес владельца, 2');
  const childSaved=(await request('/api/snapshot')).body;
  const owner=childSaved.companies.find(row=>row.name==='QA отдельный владелец');
  assert.deepEqual(owner.roles,['other']);
  assert.equal(childSaved.companies.length,beforeParties.companies.length+1);
  assert.ok(!childSaved.directories.oilDepots.some(row=>row.name==='QA нефтебаза'),'Saving the child must not submit the parent depot');
  await dialog.getByRole('button',{name:'Реквизиты: Компания — владелец нефтебазы',exact:true}).click();
  party=page.getByRole('dialog',{name:'Карточка участника погрузки',exact:true});
  await expect(party.getByLabel('Наименование',{exact:true})).toHaveValue('QA отдельный владелец');
  await party.getByLabel('Юридический адрес',{exact:true}).fill('QA юридический адрес владельца, 3');await save(party);
  await expect(dialog).toContainText('QA юридический адрес владельца, 3');
  // Existing company roles and addresses must survive the same contextual editor.
  await dialog.getByRole('button',{name:'Реквизиты: Лицо, осуществляющее погрузку',exact:true}).click();
  party=page.getByRole('dialog',{name:'Карточка участника погрузки',exact:true});
  await expect(party.getByLabel('Адрес отгрузки клиента 1',{exact:true})).toHaveValue('QA площадка');
  await party.getByLabel('Юридический адрес',{exact:true}).fill('QA юридический адрес погрузчика, 4');await save(party);
  const partiesEdited=(await request('/api/snapshot')).body;
  assert.deepEqual(partiesEdited.companies.find(row=>row.id===actorBefore.id).roles,actorBefore.roles);
  assert.deepEqual(partiesEdited.directories.addresses.filter(row=>row.companyId===actorBefore.id),actorAddresses);
  assert.deepEqual(partiesEdited.companies.find(row=>row.id===supplierBefore.id),supplierBefore);
  assert.equal(partiesEdited.companies.length,childSaved.companies.length);
  assert.deepEqual(partiesEdited.companies.find(row=>row.id===owner.id).roles,['other']);
  await expect(dialog.getByLabel('Фактический адрес места погрузки / пункта подачи',{exact:true})).toHaveValue('QA фактический адрес, 1');
  await ownerPicker.click();await expect(dialog.getByRole('option')).toHaveCount(0);
  await ownerPicker.fill('7707083893');await expect(dialog.getByRole('option')).toHaveCount(1);
  await dialog.getByRole('option').click();await expect(ownerPicker).toHaveValue('QA отдельный владелец');
  assert.ok(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth+1),'Search and participant actions overflow on mobile');
  await save(dialog);
  await page.reload();await tab('Нефтебазы');await edit('QA нефтебаза');dialog=page.getByRole('dialog',{name:'Карточка нефтебазы',exact:true});
  await expect(dialog.getByRole('combobox',{name:'Компания — владелец нефтебазы',exact:true})).toHaveValue('QA отдельный владелец');
  await expect(dialog.getByRole('combobox',{name:'Лицо, осуществляющее погрузку',exact:true})).toHaveValue('QA получатель');
  await expect(dialog.getByRole('combobox',{name:'Владелец инфраструктуры погрузки',exact:true})).toHaveValue('QA компания погрузки');
  await expect(dialog).toContainText('QA юридический адрес владельца, 3');
  await expect(dialog.getByLabel('Фактический адрес места погрузки / пункта подачи',{exact:true})).toHaveValue('QA фактический адрес, 1');
  await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
  const snapshot=(await request('/api/snapshot')).body,site=snapshot.directories.oilDepots.find(row=>row.name==='QA нефтебаза');
  assert.equal(site.ownerCompanyId,owner.id);assert.equal(site.loadingActorCompanyId,actorBefore.id);assert.equal(site.infrastructureOwnerCompanyId,supplierBefore.id);
  assert.equal((await request(`/api/directories/oilDepots/${site.id}`,'PATCH',{version:site.version??0,name:site.name,loadingActorCompanyId:'unknown-id'})).status,400);
  console.log('PASS contextual participant create/edit preserves unsaved depot, existing company roles and addresses; independent legal/actual addresses; mobile search by INN without full catalog');

  await page.setViewportSize({width:1280,height:960});await tab('Автомобили');dialog=await edit('QA машина 991');
  await expect(dialog.getByRole('combobox',{name:'Перевозчик',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
  const companiesBeforeDriver=(await request('/api/snapshot')).body.companies;
  await tab('Водители');dialog=await add();await dialog.getByLabel('ФИО водителя',{exact:true}).fill('QA водитель');
  await expect(dialog.getByRole('combobox',{name:'Перевозчик',exact:true})).toHaveCount(0);
  await choose(dialog,'Автомобиль по умолчанию *','QA машина 991');await save(dialog);
  await page.reload();await tab('Водители');dialog=await edit('QA водитель');
  await expect(dialog.getByRole('combobox',{name:'Автомобиль по умолчанию *',exact:true})).toHaveValue('QA машина 991');
  await dialog.getByLabel('Телефон водителя',{exact:true}).fill('+7 (900) 000-00-02');await save(dialog);
  const withDriver=(await request('/api/snapshot')).body,driver=withDriver.directories.drivers.find(row=>row.name==='QA водитель');
  assert.equal(driver.vehicleId,vehicle.id);assert.equal(driver.phone,'+7 (900) 000-00-02');assert.ok(!driver.carrierId);
  assert.deepEqual(withDriver.companies,companiesBeforeDriver);
  await page.getByRole('button',{name:'Удалить: QA водитель',exact:true}).click();
  await page.getByRole('dialog',{name:'Удаление записи',exact:true}).getByRole('button',{name:'Удалить',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await tab('Водители');
  await expect(page.getByRole('button',{name:'Редактировать: QA водитель',exact:true})).toHaveCount(0);
  const afterDriver=(await request('/api/snapshot')).body;
  assert.ok(!afterDriver.directories.drivers.some(row=>row.id===driver.id));
  assert.ok(afterDriver.directories.vehicles.some(row=>row.id===vehicle.id));
  assert.deepEqual(afterDriver.companies,companiesBeforeDriver);
  console.log('PASS direct driver/default-vehicle create, read, update, delete without creating a carrier company');
  assert.deepEqual(errors,[]);
} finally {
  await browser?.close();await runtime?.server.close();await rm(directory,{recursive:true,force:true});
}
