import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, writeFile, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import localApi, { loadSnapshot } from '../server/local-api.ts';
import { OperationsStore } from '../server/operations-store.ts';
import { BankHttpError } from '../server/banking/transport.ts';
import { accountNumber, dollarAccount, fixtureDay, fixtureEnvironment, sberRow, tbankRow } from '../tests/banking-fixtures.ts';
import { bootstrapQaAuth, authenticateContext } from './qa-auth.mjs';

const root = resolve(import.meta.dirname, '..'), output = resolve(root, 'qa/banking');
const temporary = await mkdtemp(resolve(tmpdir(), 'artel-banking-browser-'));
const base = 'http://127.0.0.1:5197', environment = {};
const report = { fixtureOnly: true, checks: [], errors: [], violations: [] };
const check = name => { report.checks.push(name); console.log('PASS', name); };
let failure = false, server, browser;
const store = new OperationsStore(temporary), snapshot = await loadSnapshot();
const fakeBank = async (config, path) => {
  if (failure) throw new BankHttpError(503);
  if (path.includes('/oauth/token')) return { access_token: 'fixture-access', refresh_token: 'fixture-refresh-rotated', expires_in: '3600' };
  if (path.includes('/print') || path.includes('/payment-document')) return { file: Buffer.from('%PDF-1.1\n% synthetic QA only').toString('base64'), fileData: Buffer.from('%PDF-1.1\n% synthetic QA only').toString('base64') };
  if (path.includes('/transactionId?')) return sberRow();
  if (config.definition.provider === 'sber') return { transactions: [sberRow()], _links: [] };
  const account = new URL(path, 'https://fixture.test').searchParams.get('accountNumber');
  return { operations: account === dollarAccount ? [tbankRow('dollar-payment', '12.34', dollarAccount)] : Array.from({ length: 31 }, (_, i) => tbankRow(`tbank-operation-${i}`, '0.1', accountNumber)) };
};
await mkdir(output, { recursive: true });
try {
  server = await createServer({ configFile: false, root: resolve(root, 'web'), plugins: [react(), localApi({ operationsStore: store, bankEnvironment: environment, bankRequest: fakeBank })], server: { host: '127.0.0.1', port: 5197, strictPort: true } });
  await server.listen();
  const { cookie } = await bootstrapQaAuth(base);
  const before = await store.read(snapshot.provenance.sourceSha256);
  const read = async path => { const r = await fetch(base + path, { headers: { Cookie: cookie } }); assert.ok(r.ok); return r.json(); };
  browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', timezoneId: 'Europe/Moscow', permissions: ['clipboard-read', 'clipboard-write'] });
  await authenticateContext(context, base, cookie);
  const page = await context.newPage(); page.on('pageerror', error => report.errors.push(error.message));
  await page.goto(base + '/#payments');
  await expect(page.locator('.bank-card')).toHaveCount(3);
  await expect(page.getByRole('heading', { name: 'Банковские счета ещё не подключены' })).toBeVisible();
  await page.screenshot({ path: resolve(output, 'disconnected-desktop.png'), fullPage: true }); check('Three unconfigured connections and distinct no-connection state');
  await page.getByRole('tab', { name: 'Архив из файла' }).click();
  await expect(page.locator('.payment-stats')).toBeVisible(); await expect(page.getByRole('table', { name: 'Платежи из выписки' })).toBeVisible(); check('Existing XLSX table, summaries and CSV remain available');
  await page.getByRole('tab', { name: 'Банковские подключения' }).click();
  Object.assign(environment, fixtureEnvironment, { ARTEL_BANK_SYNC_ENABLED: 'false' }); // No external network or scheduler.
  await page.reload(); await page.getByLabel('Период с', { exact: true }).fill(fixtureDay); await page.getByLabel('Период по', { exact: true }).fill(fixtureDay);
  await expect(page.getByRole('button', { name: 'Синхронизировать', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Синхронизировать', exact: true }).click();
  await expect.poll(async () => (await read(`/api/banking?from=${fixtureDay}&to=${fixtureDay}`)).total).toBe(34);
  await expect(page.locator('.bank-ledger-title')).toContainText('34 операций', { timeout: 15000 });
  await expect(page.locator('.bank-totals')).toContainText('3,10 RUB'); await expect(page.locator('.bank-totals')).toContainText('12,34 USD');
  await page.screenshot({ path: resolve(output, 'connected-desktop-fixtures.png'), fullPage: true }); check('Manual synchronization, durable continuation, per-currency summaries');
  await page.getByLabel('Операций на странице').selectOption('10'); await expect(page.locator('.bank-table tbody tr')).toHaveCount(10);
  const first = await page.locator('.bank-row-link').first().getAttribute('aria-label');
  await page.getByRole('button', { name: 'Следующая страница операций' }).click();
  await expect(page.locator('.bank-pagination')).toContainText('11–20'); assert.notEqual(await page.locator('.bank-row-link').first().getAttribute('aria-label'), first); check('Pagination changes rows and keeps totals');
  await page.getByRole('button', { name: 'Открыть СберБизнес — НК АРТЕЛЬ' }).click();
  await expect(page.locator('.bank-table tbody tr')).toHaveCount(1); await expect(page.locator('.bank-table')).toContainText('Списание');
  await page.getByRole('button', { name: 'Открыть платёж 42' }).click();
  await expect(page.getByRole('dialog')).toBeVisible(); await expect(page.locator('.bank-parties')).toContainText('КОМПЛЕКС — ОЙЛ');
  await expect(page.locator('.bank-payment-sum')).toContainText('Списание');
  await page.getByRole('button', { name: 'Копировать Получатель · ИНН', exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), '7800000000');
  await page.getByText('Все доступные поля банковского ответа', { exact: true }).click(); await expect(page.locator('.bank-raw-details')).toContainText('test-uip');
  await page.screenshot({ path: resolve(output, 'payment-detail-fixtures.png'), fullPage: true });
  await expect(page.getByRole('button', { name: 'Печатная форма банка', exact: true })).toBeEnabled();
  const fileEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'Печатная форма банка', exact: true }).click();
  const pdf = await fileEvent; assert.ok((await readFile(await pdf.path())).toString().startsWith('%PDF-')); check('Bank -> operation -> detail; correct parties, copying, raw fields and synthetic PDF route');
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Все подключения', exact: true }).click();
  await page.getByRole('button', { name: 'Открыть Т-Банк — НК АРТЕЛЬ' }).click();
  await page.getByLabel('Наш счёт', { exact: true }).selectOption(dollarAccount);
  await expect(page.locator('.bank-table tbody tr')).toHaveCount(1); await expect(page.locator('.bank-totals')).not.toContainText('RUB'); check('Account filter and currency-separated totals');
  await page.getByRole('button', { name: 'Сбросить', exact: true }).click();
  await page.getByLabel('Поиск банковских операций').fill('7812345678');
  await expect(page.locator('.bank-ledger-title')).toContainText('32 операций');
  await page.getByLabel('Поиск банковских операций').fill('tbank-operation-2');
  await expect(page.locator('.bank-ledger-title')).toContainText('11 операций');
  const csvEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'Экспорт CSV', exact: true }).click();
  const exported = await csvEvent; assert.equal((await readFile(await exported.path(), 'utf8')).split('\r\n').length, 12); check('Search by INN and purpose; export contains all filtered pages');
  await page.getByLabel('Поиск банковских операций').fill('нет-такого-платежа'); await expect(page.getByRole('heading', { name: 'По вашему запросу ничего не найдено' })).toBeVisible();
  await page.getByRole('button', { name: 'Сбросить фильтры', exact: true }).click();
  await page.getByLabel('Направление операции').selectOption('outgoing'); await expect(page.getByRole('heading', { name: 'По вашему запросу ничего не найдено' })).toBeVisible();
  await page.getByRole('button', { name: 'Сбросить фильтры', exact: true }).click(); check('Distinct no-results state and direction filter');
  failure = true;
  await page.getByRole('button', { name: 'Синхронизировать', exact: true }).click();
  await expect(page.getByRole('alert').first()).toContainText('временно недоступен'); await expect(page.locator('.bank-ledger-title')).toContainText('32 операций'); check('Bank failure retains already synchronized data and exposes retry state');
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `page overflow ${width}`);
    await page.screenshot({ path: resolve(output, `operations-${width}-fixtures.png`), fullPage: true });
  }
  failure = false;
  await page.setViewportSize({width:1440,height:1000});
  const axe = await new AxeBuilder({ page }).include('.banking-page').withTags(['wcag2a','wcag2aa']).analyze();
  report.violations = axe.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => ({target:n.target,failureSummary:n.failureSummary})) }));
  check('Browser checks at 1440, 768, 390 and 320 px');
  const after = await store.read(snapshot.provenance.sourceSha256);
  for (const key of ['shipments','companies','directories','paymentAllocations']) assert.deepEqual(after[key], before[key]);
  assert.equal(report.errors.length, 0); check('No JavaScript errors; existing business data unchanged in isolated storage');
  assert.equal(report.violations.length, 0, 'Banking accessibility audit');
  report.status = 'passed';
} catch (error) { report.status = 'failed'; report.failure = error.message; throw error; }
finally { await writeFile(resolve(output, 'verification.json'), JSON.stringify(report, null, 2)); await browser?.close(); await server?.close(); await rm(temporary, { recursive:true, force:true }); }
