import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
const base = process.env.ARTEL_TEST_URL || 'http://127.0.0.1:5173';
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await chromium.launch({headless:true,...(existsSync(chrome)?{executablePath:chrome}:{})});
const context = await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page = await context.newPage();
const errors = [];
const checks = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', e => {if(e.type()==='error') errors.push(e.text())});
await mkdir('qa/ui',{recursive:true});
const data = await (await fetch(base+'/api/snapshot')).json();
const routeTitles={overview:'Обзор бизнеса.',shipments:'Отгрузки.',payments:'Платежи.',stock:'Склад.',quality:'Проверка данных.',team:'Команда и роли.'};
const go = async route => {await page.goto(base+'/#'+route);await expect(page.locator('h1')).toHaveText(routeTitles[route]);await page.locator('.page-content').waitFor();if(route==='shipments') await page.locator('[data-testid="shipment-row"]').first().waitFor();if(route==='overview') await page.locator('tbody tr').first().waitFor();};
try {
  await go('overview');
  await expect(page.locator('.stats-grid')).toContainText('2 092');
  await page.getByLabel('Период',{exact:true}).selectOption('2026-08');
  await expect(page.locator('.stats-grid')).toContainText('135');
  await expect(page.locator('.bar-column.highlight')).toHaveCount(1);
  await page.getByRole('button',{name:'Литры',exact:true}).click();
  await expect(page.locator('.chart-key')).toContainText('Объём отгрузок');
  checks.push('dashboard, period, metric switch');
  await page.getByLabel('Глобальный поиск контрагентов').fill('ИНПРОФСТРОЙ');
  await page.getByLabel('Глобальный поиск контрагентов').press('Enter');
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.locator('.company-search-results')).toContainText('ИНПРОФСТРОЙ');
  await page.locator('.company-search-result').first().click();
  await expect(page.getByRole('dialog')).toContainText('ИНПРОФСТРОЙ');
  await page.getByRole('dialog').getByRole('button',{name:/Отгрузки/}).click();
  await expect(page.locator('.dialog-records>button').first()).toBeVisible();
  await page.locator('.dialog-records>button').first().click();
  await expect(page.getByRole('dialog')).toContainText('ЗАПИСЬ ИЗ EXCEL');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  checks.push('global company lookup, company card, lazy linked shipment, Escape');
  await go('shipments');
  await expect(page.locator('.sidebar').getByRole('button',{name:'Контрагенты',exact:true})).toHaveCount(0);
  checks.push('counterparty page removed, company data retained');
  await go('payments');
  await page.getByLabel('Период',{exact:true}).selectOption('all');
  await page.getByLabel('Направление платежа').selectOption('undated');
  await expect(page.locator('.pagination')).toContainText('70');
  await page.getByLabel('Направление платежа').selectOption('outgoing');
  await page.getByLabel('Контрагент или назначение…').fill('2322');
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody')).toContainText('-5 900 000');
  const csvDownload = page.waitForEvent('download');
  await page.getByRole('button',{name:'Экспорт CSV',exact:true}).click();
  const csv = await csvDownload;
  await csv.saveAs('qa/ui/payment-test.csv');
  const csvText = await readFile('qa/ui/payment-test.csv','utf8');
  assert(csvText.includes('"-5900000"'));
  assert(!csvText.includes("'-5900000"));
  checks.push('undated payments, negative reversal, CSV content');
  await go('stock');
  await page.getByLabel('Объект склада').selectOption({label:data.stocks[0].label});
  await page.getByLabel('Месяц складской сводки').selectOption('8');
  await expect(page.locator('.sp-stock-table tbody>tr')).toHaveCount(1);
  await page.locator('.sp-source-link').first().click();
  await expect(page.locator('.sp-value-grid')).toBeVisible();
  const jsonDownload = page.waitForEvent('download');
  await page.getByRole('button',{name:'Экспорт JSON'}).click();
  const json = await jsonDownload;
  await json.saveAs('qa/ui/stock-test.json');
  assert.equal(JSON.parse(await readFile('qa/ui/stock-test.json','utf8')).stocks.length,1);
  checks.push('stock filters, source details, JSON content');
  await go('quality');
  await page.screenshot({path:'qa/ui/quality-desktop.png',fullPage:true,animations:'disabled'});
  await page.locator('.sp-source-link').first().click();
  await expect(page.locator('.sp-detail-content')).toBeVisible();
  checks.push('quality source expansion');
  await go('team');
  await page.getByRole('button',{name:/Менеджер Свои компании/}).click();
  await expect(page.locator('.team-role-detail')).toContainText('Менеджер');
  await page.screenshot({path:'qa/ui/team-desktop.png',fullPage:true,animations:'disabled'});
  checks.push('role interaction');
  for(const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:900});
    for(const route of ['overview','shipments','payments','stock','quality','team']) {
      await go(route);
      const dimensions=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));
      assert(dimensions.document<=dimensions.viewport+1,`horizontal overflow ${route} at ${width}: ${dimensions.document}`);
      assert.equal(await page.locator('h1').count(),1,`${route} h1 count`);
      if(width===390) await page.screenshot({path:`qa/ui/${route}-mobile.png`,fullPage:true,animations:'disabled'});
      if(width===1440&&route==='overview') await page.screenshot({path:'qa/ui/overview-desktop.png',fullPage:true,animations:'disabled'});
    }
  }
  await page.setViewportSize({width:320,height:720});
  await go('overview');
  await page.getByRole('button',{name:'Открыть меню',exact:true}).click();
  await page.getByRole('button',{name:/^Отгрузки/}).click();
  await expect(page).toHaveURL(/#shipments$/);
  await expect(page.locator('.sidebar')).not.toHaveClass(/is-open/);
  checks.push('24 responsive route checks, mobile menu');
  assert.equal(errors.length,0,errors.join('\n'));
  const raw = await fetch(base+'/@fs/Users/mustafa/Desktop/Artel-CRM/data/local-xlsx-final/raw_workbook.json');
  assert.equal(raw.status,403);
  const publicPath=await fetch(base+'/data/local-xlsx-final/raw_workbook.json');
  assert(!(publicPath.headers.get('content-type')||'').includes('application/json'));
  checks.push('no console errors, raw workbook not publicly served');
  await writeFile('qa/ui-verification.json',JSON.stringify({status:'passed',base,checkedAt:new Date().toISOString(),checks,consoleErrors:errors},null,2));
  console.log(JSON.stringify({status:'passed',checks},null,2));
} catch(error) {
  await page.screenshot({path:'qa/ui/failure.png',fullPage:true,animations:'disabled'});
  await writeFile('qa/ui-verification.json',JSON.stringify({status:'failed',checks,error:String(error),consoleErrors:errors},null,2));
  throw error;
} finally {await browser.close();}
