import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { tsImport } from 'tsx/esm/api';
const root=resolve(import.meta.dirname,'..'),port=5187,url=`http://127.0.0.1:${port}`;
const output=resolve(root,'qa/directories-2026-09-10');await mkdir(output,{recursive:true});
const directory=await mkdtemp(resolve(tmpdir(),'artel-directories-ui-'));
const {OperationsStore}=await tsImport('../server/operations-store.ts',import.meta.url);
const {loadSnapshot}=await tsImport('../server/local-api.ts',import.meta.url);
const {clearOperations}=await tsImport('../server/reset-operations.ts',import.meta.url);
const base=await loadSnapshot(resolve(root,'data/local-xlsx-final')),store=new OperationsStore(directory);
await store.mutate(base.provenance.sourceSha256,data=>({result:clearOperations(base,data),changed:true}));
const file=resolve(root,'data/local-operations/operations.json');
const hash=async()=>existsSync(file)?createHash('sha256').update(await readFile(file)).digest('hex'):null;
const before=await hash(),report={checks:[],screenshots:[],measurements:[],errors:[],temporaryStore:directory};
const check=(name)=>{report.checks.push(name);console.log('PASS',name)};
let server,browser,page;
try{
  await assert.rejects(fetch(url,{signal:AbortSignal.timeout(500)}));
  server=spawn(process.execPath,[resolve(root,'node_modules/vite/bin/vite.js'),'preview','--host','127.0.0.1','--port',String(port),'--strictPort'],{cwd:root,env:{...process.env,ARTEL_STORE_DIR:directory,CHECKO_API_KEY:''},stdio:'ignore'});
  for(let i=0;i<100;i++){try{if((await fetch(url+'/api/snapshot?shipments=omit')).ok)break}catch{}await new Promise(done=>setTimeout(done,100))}
  browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.on('pageerror',error=>report.errors.push(error.message));
  const shot=async(name)=>{const path=resolve(output,name+'.png');await page.screenshot({path,fullPage:true});report.screenshots.push(path)};
  const choose=async(scope,label,name)=>{const picker=scope.getByRole('combobox',{name:new RegExp('^'+label)});await picker.click();await picker.fill(name);await scope.getByRole('listbox').getByRole('option').first().click();await expect(picker).toHaveValue(name)};
  const openTab=async(name)=>{await page.getByRole('group',{name:'Справочники',exact:true}).getByRole('button',{name,exact:true}).click()};
  await page.goto(url+'/#directories');await expect(page.locator('.directory-record').first()).toBeVisible();
  assert.equal(await page.getByRole('group',{name:'Справочники',exact:true}).getByRole('button').count(),5);
  await expect(page.locator('.directory-editor')).toHaveCount(0);await expect(page.getByText(/рабочее пространство|Артэль|Топливный бизнес|Возможные дубли|Проверка данных/i)).toHaveCount(0);
  check('five directories, no permanent forms or removed sections');
  const initial=await(await fetch(url+'/api/snapshot')).json();const manager=initial.directories.managers[0].name,secondManager=initial.directories.managers[1].name;
  await page.getByRole('button',{name:'Добавить',exact:true}).click();let dialog=page.getByRole('dialog');
  await dialog.getByLabel('Наименование',{exact:true}).fill('QA Компания карточки');await dialog.getByLabel('ИНН',{exact:true}).fill('123');
  await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('корректный ИНН');
  await dialog.getByLabel('ИНН',{exact:true}).fill('7707083893');await dialog.getByRole('button',{name:'Заполнить из Чекко'}).click();await expect(dialog.getByRole('alert')).toContainText('CHECKO_API_KEY');await expect(dialog.getByLabel('Наименование',{exact:true})).toHaveValue('QA Компания карточки');
  await page.route('**/api/companies/lookup',route=>route.fulfill({json:{company:{name:'QA Компания карточки',inn:'7707083893',fullName:'Полное имя QA',kpp:'770701001',ogrn:'1027700132195',director:'QA Директор',address:'QA Юридический адрес'}}}));
  await dialog.getByRole('button',{name:'Заполнить из Чекко'}).click();await expect(dialog.getByLabel('Генеральный директор',{exact:true})).toHaveValue('QA Директор');await expect(dialog.getByRole('status')).toContainText('заполнены из Чекко');await page.unroute('**/api/companies/lookup');
  assert.equal((await(await fetch(url+'/api/snapshot')).json()).companies.length,initial.companies.length);
  await choose(dialog,'Менеджер компании',manager);await dialog.getByLabel('Поставщик',{exact:true}).check();
  const loading=dialog.locator('.company-address-group').filter({hasText:'Фактические адреса загрузки поставщика'});await loading.getByRole('button',{name:'Добавить адрес'}).click();await dialog.getByLabel('Адрес загрузки 1',{exact:true}).fill('QA Загрузка один');await loading.getByRole('button',{name:'Добавить адрес'}).click();await dialog.getByLabel('Адрес загрузки 2',{exact:true}).fill('QA Загрузка два');
  await dialog.locator('.company-address-group').filter({hasText:'Фактические адреса отгрузки клиента'}).getByRole('button',{name:'Добавить адрес'}).click();await dialog.getByLabel('Адрес отгрузки клиента 1',{exact:true}).fill('QA Отгрузка клиента');
  await dialog.locator('summary').filter({hasText:'Контакты и банковские реквизиты'}).click();await dialog.getByLabel('Телефон компании',{exact:true}).fill('+7 (900) 000-00-00');await dialog.getByLabel('Электронная почта',{exact:true}).fill('qa@example.test');await dialog.getByLabel('Банк клиента',{exact:true}).fill('QA Банк');await dialog.getByLabel('Расчётный счёт',{exact:true}).fill('00000000000000000000');
  await shot('company-create');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByLabel('Поиск в справочнике',{exact:true}).fill('QA Компания карточки');await page.getByRole('button',{name:'Редактировать: QA Компания карточки',exact:true}).click();dialog=page.getByRole('dialog');
  await expect(dialog.getByRole('combobox',{name:'Менеджер компании',exact:true})).toHaveValue(manager);await expect(dialog.getByLabel('Адрес загрузки 2',{exact:true})).toHaveValue('QA Загрузка два');await choose(dialog,'Менеджер компании',secondManager);await dialog.getByLabel('Наименование',{exact:true}).fill('QA Компания изменена');await dialog.getByLabel('Адрес загрузки 1',{exact:true}).fill('QA Загрузка изменена');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);await page.reload();await page.getByLabel('Поиск в справочнике',{exact:true}).fill('QA Компания изменена');await expect(page.locator('.directory-record')).toHaveCount(1);await expect(page.locator('.directory-record')).toContainText(secondManager);
  check('company create/edit/reload, manager, multiple addresses, bank fields, errors and Checko draft flow (provider mocked for success)');
  await page.getByRole('button',{name:'Редактировать: QA Компания изменена',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Наименование',{exact:true}).fill('НЕ СОХРАНЯТЬ');await page.keyboard.press('Escape');await expect(dialog.getByRole('alert')).toContainText('без сохранения');await dialog.getByRole('button',{name:'Продолжить редактирование'}).click();await expect(dialog.getByLabel('Наименование',{exact:true})).toHaveValue('НЕ СОХРАНЯТЬ');await dialog.getByRole('button',{name:'Отмена',exact:true}).click();await dialog.getByRole('button',{name:'Не сохранять',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);check('unsaved card changes require an explicit discard');
  await page.getByLabel('Глобальный поиск контрагентов',{exact:true}).fill('QA Компания изменена');await page.getByRole('button',{name:'Найти контрагента',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.locator('.company-search-result')).toHaveCount(1);await dialog.locator('.company-search-result').click();await expect(page.getByRole('dialog').getByRole('heading',{name:'QA Компания изменена',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toContainText(secondManager);await page.getByRole('button',{name:'Закрыть карточку',exact:true}).click();
  await page.getByLabel('Глобальный поиск контрагентов',{exact:true}).press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Закрыть поиск'}).click();await page.keyboard.press('Meta+k');await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Закрыть поиск'}).click();check('header search button, Enter and Cmd+K open matching company');
  await openTab('Менеджеры');await page.getByRole('button',{name:'Добавить',exact:true}).click();await page.getByLabel('Имя менеджера',{exact:true}).fill('QA Новый менеджер');await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Редактировать: QA Новый менеджер',exact:true}).click();await page.getByLabel('Имя менеджера',{exact:true}).fill('QA Менеджер изменён');await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('button',{name:'Редактировать: QA Менеджер изменён',exact:true})).toBeVisible();
  await openTab('Товары');await page.getByRole('button',{name:'Добавить',exact:true}).click();await page.getByLabel('Название товара',{exact:true}).fill('QA Топливо');await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Редактировать: QA Топливо',exact:true}).click();await page.getByLabel('Название товара',{exact:true}).fill('QA Топливо изменено');await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);check('manager and product add/edit');
  await openTab('Водители');const driver=initial.directories.drivers[0];await page.getByRole('button',{name:`Редактировать: ${driver.name}`,exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('ФИО водителя',{exact:true}).fill('QA Водитель изменён');await dialog.locator('summary').filter({hasText:'Паспортные данные водителя'}).click();await dialog.getByLabel('Серия паспорта',{exact:true}).fill('0000');await dialog.getByLabel('Номер паспорта',{exact:true}).fill('000000');await dialog.getByLabel('Кем выдан паспорт',{exact:true}).fill('QA Отдел');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);
  await openTab('Автомобили');const vehicle=initial.directories.vehicles[0];await page.getByRole('button',{name:`Редактировать: ${vehicle.name||vehicle.plate}`,exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Название для выбора',{exact:true}).fill('QA Машина');await dialog.locator('summary').filter({hasText:'Свидетельство о регистрации'}).click();await dialog.getByLabel('Номер СТС',{exact:true}).fill('000000');await dialog.locator('summary').filter({hasText:'Паспорт транспортного средства'}).click();await dialog.getByLabel('Номер ПТС / ЭПТС',{exact:true}).fill('000000000000000');await shot('vehicle-documents');await dialog.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(dialog).toHaveCount(0);await page.reload();
  const afterFleet=await(await fetch(url+'/api/snapshot')).json();assert.equal(afterFleet.directories.drivers.length,initial.directories.drivers.length);assert.equal(afterFleet.directories.vehicles.length,initial.directories.vehicles.length);assert.equal(afterFleet.directories.drivers.find(row=>row.id===driver.id).passportSeries,'0000');assert.equal(afterFleet.directories.vehicles.find(row=>row.id===vehicle.id).ptsNumber,'000000000000000');check('driver passport and vehicle STS/PTS persist without seed duplicates');
  await page.getByRole('button',{name:'Свернуть панель',exact:true}).click();await expect(page.locator('.sidebar')).toHaveCSS('width','76px');await page.reload();await expect(page.locator('.sidebar')).toHaveCSS('width','76px');
  for(const [name,hash] of [['Обзор','overview'],['Платежи','payments'],['Склад','stock'],['Команда и роли','team'],['Справочники','directories'],['Отгрузки','shipments']]){await page.locator('.sidebar').getByRole('button',{name,exact:true}).click();await expect(page).toHaveURL(new RegExp('#'+hash+'$'));}
  await expect(page.getByRole('button',{name:/полноэкран/i})).toHaveCount(0);await expect(page.locator('.topbar')).toBeHidden();await expect(page.getByRole('button',{name:'Открыть меню',exact:true})).toBeVisible();check('sidebar collapse persists and all six icons navigate including full-screen shipments');
  await page.getByRole('button',{name:'Добавить отгрузку',exact:true}).click();dialog=page.getByRole('dialog');await choose(dialog,'Поставщик','QA Компания изменена');await choose(dialog,'Место загрузки','QA Загрузка изменена');await dialog.getByLabel('Цена поставщика за тонну, ₽',{exact:false}).fill('60000');await dialog.getByLabel('Тоннаж всей машины, т',{exact:false}).fill('1');await choose(dialog,'Товар','QA Топливо изменено');await choose(dialog,'Клиент','QA Компания изменена');await choose(dialog,'Форма оплаты','б/нал');await expect(dialog.getByRole('combobox',{name:/^Менеджер/})).toHaveValue(secondManager);await choose(dialog,'Место выгрузки','QA Отгрузка клиента');await dialog.getByLabel('Количество литров, л',{exact:false}).fill('1200');await dialog.getByLabel('Цена за литр, ₽',{exact:false}).fill('65');await choose(dialog,'Перевозчик / водитель','QA Водитель изменён');await dialog.getByRole('button',{name:'Сохранить отгрузку',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByTestId('shipment-row')).toHaveCount(1);check('new truck after reset uses updated companies, manager, addresses, product, driver and vehicle');
  for(const width of [1440,1024,768,390,320]){
    await page.setViewportSize({width,height:1000});
    for(const hash of ['shipments','directories','overview','payments','stock','team']){
      await page.goto(url+'/#'+hash);await expect(page.locator('.page-content')).toBeVisible();
      const measurement=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,sidebar:document.querySelector('.sidebar').getBoundingClientRect().width}));report.measurements.push({hash,...measurement});assert.ok(measurement.document<=width+1,JSON.stringify({hash,...measurement}));
      if(hash==='directories'||hash==='shipments')await shot(`${hash}-${width}`);
    }
    await page.goto(url+'/#directories');await page.getByRole('button',{name:'Добавить',exact:true}).click();dialog=page.getByRole('dialog');const box=await dialog.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width+1,JSON.stringify(box));await shot(`company-dialog-${width}`);await dialog.getByRole('button',{name:'Отмена',exact:true}).click();
    if(width<761){await page.getByRole('button',{name:'Открыть меню',exact:true}).click();await expect(page.locator('.sidebar')).toBeInViewport();await page.locator('.sidebar').getByRole('button',{name:'Отгрузки',exact:true}).click();await expect(page).toHaveURL(/#shipments$/);await expect(page.locator('.sidebar')).not.toBeInViewport();}
  }check('all six pages and company dialog responsive at 1440/1024/768/390/320; mobile navigation works');
  assert.deepEqual(report.errors,[]);assert.equal(await hash(),before);check('no page errors and live operations store unchanged by QA');
}catch(error){report.failure=error.stack;try{await page?.screenshot({path:resolve(output,'failure.png'),fullPage:true})}catch{}throw error}
finally{await writeFile(resolve(output,'verification.json'),JSON.stringify(report,null,2));await browser?.close();server?.kill('SIGTERM')}
