import { useEffect, useState, type ReactNode } from 'react';
import type { AccountUser, SessionState } from './auth-model';
import { currentPushEndpoint, disconnectPushDevice } from './push-client';
import './auth.css';
export default function AuthGate({children}:{children:(user:AccountUser,onLogout:()=>void)=>ReactNode}){
  const [session,setSession]=useState<SessionState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [form,setForm]=useState({name:'',login:'',password:'',setupToken:''});
  const refresh=()=>fetch('/api/auth/session').then(async r=>{if(!r.ok)throw new Error('Не удалось проверить доступ.');setSession(await r.json());setError('');}).catch(e=>setError(e.message));
  useEffect(()=>{void refresh();const focus=()=>{void refresh();};window.addEventListener('focus',focus);const timer=setInterval(focus,60000);return()=>{window.removeEventListener('focus',focus);clearInterval(timer);};},[]);
  const logout=async()=>{setBusy(true);try{const r=await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pushEndpoint:await currentPushEndpoint().catch(()=>null)})});if(!r.ok && r.status!==401)throw new Error('Не удалось завершить сеанс.');await disconnectPushDevice().catch(()=>undefined);setSession(s=>s?{...s,user:null}:s);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(session?.user)return children(session.user,()=>{if(!busy)void logout();});
  return <main className="auth-screen"><section className="panel auth-card"><span className="eyebrow">АРТЕЛЬ CRM</span><h1>{session?.needsSetup?'Первый вход':'Вход'}</h1>{session?.needsSetup&&<p>Создайте учётную запись директора для работы с CRM.</p>}{error&&<p className="soft-notice" role="alert">{error}</p>}{!session?<button className="button" onClick={()=>void refresh()}>Повторить загрузку</button>:<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const payload=session.needsSetup?form:{login:form.login,password:form.password};const r=await fetch(`/api/auth/${session.needsSetup?'setup':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const v=await r.json();if(!r.ok)throw new Error(v.error||'Не удалось войти.');setForm({name:'',login:'',password:'',setupToken:''});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
    <fieldset disabled={busy}>{session.needsSetup&&<label>Имя<input required maxLength={120} autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Логин<input required autoComplete="username" maxLength={64} value={form.login} onChange={e=>setForm({...form,login:e.target.value})}/></label><label>Пароль<input required type="password" minLength={session.needsSetup?12:undefined} maxLength={256} autoComplete={session.needsSetup?'new-password':'current-password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{session.needsSetup&&session.setupTokenRequired&&<label>Ключ первоначальной настройки<input required type="password" autoComplete="off" value={form.setupToken} onChange={e=>setForm({...form,setupToken:e.target.value})}/></label>}<button className="button primary" type="submit">{busy?'Подождите…':session.needsSetup?'Создать директора':'Войти'}</button></fieldset></form>}</section></main>;
}
