import { useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';
const names: Record<string,string> = { customers: 'Клиенты', suppliers: 'Поставщики', managers: 'Менеджеры', products: 'Товары', vehicles: 'Автомобили', drivers: 'Водители' };
export default function DirectoryCleanup({ onClose, onDone }: { onClose: () => void; onDone: (backup: string) => void }) {
  const dialog = useRef<HTMLDialogElement>(null), busy = useRef(false);
  const [preview, setPreview] = useState<{ counts?: Record<string,number>; revision: number; blocked?: string; available: boolean } | null>(null);
  const [error, setError] = useState(''), [saving, setSaving] = useState(false);
  useEffect(() => { const element = dialog.current; element?.showModal(); const controller = new AbortController(); void fetch('/api/directories/cleanup', { signal: controller.signal, cache: 'no-store' }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Не удалось проверить связи.'); setPreview(result); }).catch(reason => { if (!controller.signal.aborted) setError(reason.message); }); return () => { controller.abort(); element?.close(); }; }, []);
  const close = () => { if (!busy.current) onClose(); };
  return <dialog ref={dialog} className="detail-dialog directory-delete-dialog" aria-labelledby="cleanup-title" onCancel={event => { event.preventDefault(); close(); }}><header className="directory-editor-heading"><h2 id="cleanup-title">Очистка справочников</h2><button type="button" className="icon-button" disabled={saving} aria-label="Закрыть очистку" onClick={close}><X size={20}/></button></header><div className="directory-editor-body"><p>Перед очисткой будет создана и проверена резервная копия. Формы добавления сохранятся. Платежи, отгрузки, задачи, три постоянные формы оплаты, команды и роли не очищаются.</p><p>Адреса компаний и назначения менеджеров удаляются вместе с очищаемыми записями. Если запись нужна документам, задачам или учётной записи сотрудника, вся операция отменяется.</p>{!preview && !error && <p>Проверяем связи…</p>}{preview?.counts && <ul>{Object.entries(preview.counts).map(([kind, count]) => <li key={kind}>{names[kind]}: {count}</li>)}</ul>}{preview?.blocked && <p role="alert" className="shipment-error">{preview.blocked} Связанные документы не удалены.</p>}{preview && !preview.available && !preview.blocked && <p role="alert">Резервное копирование недоступно. Очистка запрещена.</p>}{error && <p role="alert" className="shipment-error">{error}</p>}</div><footer className="directory-editor-footer"><button className="button" disabled={saving} onClick={close}>Отмена</button><button className="button directory-danger" disabled={!preview?.available || saving || !!error} onClick={async () => {
    if (!preview || busy.current) return; busy.current = true; setSaving(true); setError('');
    try { const response = await fetch('/api/directories/cleanup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: 'clear-directories', revision: preview.revision }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Очистка не выполнена.'); onDone(result.backup); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Нет связи с сервером.'); } finally { busy.current = false; setSaving(false); }
  }}>{saving ? 'Создание копии и очистка…' : 'Создать копию и очистить'}</button></footer></dialog>;
}
