import { useState } from 'react'
import { LoaderCircle, Plus, Search } from 'lucide-react'
import type { Snapshot, Vehicle } from './model'
import DirectorySelect from './DirectorySelect'
import CustomerManagersDirectory from './CustomerManagersDirectory'
const tabs = [{id:'companies',name:'Компании'},{id:'customerManagers',name:'Клиенты и менеджеры'},{id:'managers',name:'Менеджеры'},{id:'products',name:'Товары'},{id:'paymentForms',name:'Формы оплаты'},{id:'vehicles',name:'Автомобили'},{id:'drivers',name:'Водители'},{id:'addresses',name:'Адреса'},{id:'duplicates',name:'Возможные дубли'}] as const
const litres = (value: string) => `${Number(value).toLocaleString('ru-RU')} л`
const vehicleName = (vehicle: Vehicle) => vehicle.name || vehicle.plate
const vehicleDetail = (vehicle: Vehicle) => [vehicle.name && vehicle.name !== vehicle.plate ? vehicle.plate : '', ...(!vehicle.name ? [vehicle.brand, vehicle.model] : []), vehicle.trailer, vehicle.capacityLitres ? `Объём: ${litres(vehicle.capacityLitres)}` : 'Объём не указан', vehicle.compartmentsLitres?.length ? `Секции: ${vehicle.compartmentsLitres.map(value => Number(value).toLocaleString('ru-RU')).join(' + ')} л` : ''].filter(Boolean).join(' · ')
export default function DirectoriesPage({data,onChanged}:{data:Snapshot;onChanged:()=>void}) {
  const [tab,setTab]=useState<(typeof tabs)[number]['id']>('companies'),[query,setQuery]=useState(''),[fields,setFields]=useState<Record<string,string>>({addressKind:'delivery'}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
  const catalog=data.directories!
  const update=(key:string,value:string)=>setFields(old=>({...old,[key]:value}))
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(saving)return;setSaving(true);setError('');setNotice('');try{
    const payload: Record<string, unknown> = tab==='companies'?{inn:fields.inn}:{kind:tab,...fields}
    if(tab==='vehicles') {
      if(fields.compartmentsLitres?.trim()) payload.compartmentsLitres=fields.compartmentsLitres.split(/[+;]/).map(value=>value.trim())
      else delete payload.compartmentsLitres
    }
    const response=await fetch(tab==='companies'?'/api/companies/from-inn':'/api/directories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Не удалось сохранить запись');setNotice(result.created?'Запись добавлена':'Такая запись уже есть — дубль не создан');setFields(tab==='addresses'?{addressKind:fields.addressKind,companyId:fields.companyId}:{});onChanged()
  }catch(e){setError(e instanceof Error?e.message:'Нет связи с сервером')}finally{setSaving(false)}}
  const input=(label:string,key:string,required=true)=><label className="shipment-field"><span>{label}</span><input aria-label={label} value={fields[key]??''} required={required} disabled={saving} onChange={e=>update(key,e.target.value)}/></label>
  const navigation = <div className="directory-tabs" role="group" aria-label="Справочники">{tabs.map(t=><button className={`button ${t.id===tab?'primary':''}`} aria-pressed={t.id===tab} key={t.id} onClick={()=>{setTab(t.id);setFields(t.id==='addresses'?{addressKind:'delivery'}:{});setError('');setNotice('');setQuery('')}}>{t.name}{t.id==='duplicates'&&` · ${catalog.duplicates.length}`}</button>)}</div>
  if (tab === 'customerManagers') return <div className="directories-page">{navigation}<CustomerManagersDirectory data={data} onChanged={onChanged}/></div>
  const rows=tab==='companies'?data.companies.map(c=>({id:c.id,name:c.name,detail:c.inn?`ИНН ${c.inn}`:'ИНН не указан'})):tab==='vehicles'?catalog.vehicles.map(v=>({id:v.id,name:vehicleName(v),detail:vehicleDetail(v)})):tab==='drivers'?catalog.drivers.map(d=>({id:d.id,name:d.name,detail:[d.phone,catalog.vehicles.find(v=>v.id===d.vehicleId)].map(value=>typeof value==='object'?vehicleName(value):value).filter(Boolean).join(' · ')})):tab==='addresses'?catalog.addresses.map(a=>({id:a.id,name:a.name,detail:`${a.kind==='loading'?'Загрузка':'Выгрузка'} · ${data.companies.find(c=>c.id===a.companyId)?.name}`})):tab==='duplicates'?catalog.duplicates.map((g,i)=>({id:String(i),name:g.names.join(' / '),detail:g.reason})):catalog[tab]
  const visible=rows.filter(r=>`${r.name} ${'detail'in r?r.detail:''}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')))
  return <div className="directories-page">{navigation}
    {tab!=='duplicates'&&<form className="panel directory-create" onSubmit={save}><h2>Добавить: {tabs.find(t=>t.id===tab)?.name.toLocaleLowerCase('ru')}</h2><div className="shipment-field-grid">
      {tab==='companies'?input('ИНН компании','inn'):tab==='vehicles'?<>{input('Автомобиль / номер','plate')}{input('Название для выбора','name',false)}{input('Марка','brand',false)}{input('Модель','model',false)}{input('Прицеп','trailer',false)}{input('Объём автомобиля, л','capacityLitres',false)}{input('Секции, л (через +)','compartmentsLitres',false)}</>:<>{input(tab==='drivers'?'ФИО водителя':tab==='addresses'?'Адрес / название точки':'Название','name')}{tab==='drivers'&&<>{input('Телефон водителя','phone',false)}<DirectorySelect label="Автомобиль по умолчанию" entries={catalog.vehicles.map(v=>({id:v.id,name:vehicleName(v),detail:vehicleDetail(v)}))} value={fields.vehicleId??''} onChange={id=>update('vehicleId',id)} required disabled={saving}/></>} {tab==='addresses'&&<><DirectorySelect label="Компания" entries={data.companies.map(c=>({id:c.id,name:c.name,detail:c.inn}))} value={fields.companyId??''} onChange={id=>update('companyId',id)} required disabled={saving}/><label className="shipment-field"><span>Тип адреса</span><select aria-label="Тип адреса" value={fields.addressKind} disabled={saving} onChange={e=>update('addressKind',e.target.value)}><option value="delivery">Выгрузка у покупателя</option><option value="loading">Загрузка у поставщика</option></select></label></>}</>}
      </div><button className="button primary" type="submit" disabled={saving}>{saving?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>}Добавить в справочник</button>{tab==='companies'&&<p className="shipment-editor-note">Реквизиты поступают из Чекко. Совпадение ИНН возвращает существующую фирму; одинаковые названия без ИНН требуют проверки.</p>}</form>}
    {error&&<p className="shipment-error" role="alert">{error}</p>}{notice&&<p className="soft-notice" role="status">{notice}</p>}
    {tab==='duplicates'&&<p className="soft-notice">Ниже — кандидаты на объединение. Без подтверждения ИНН одинаковое название не доказывает, что это одна фирма. Исходные записи и связи отгрузок сохранены.</p>}
    <section className="panel directory-list"><label className="shipment-search"><Search size={17}/><input aria-label="Поиск в справочнике" placeholder="Найти запись…" value={query} onChange={e=>setQuery(e.target.value)}/></label><p className="shipment-editor-note">Записей: {visible.length}</p><div className="directory-rows">{visible.map(r=><div key={r.id}><strong>{r.name}</strong>{'detail'in r&&<span>{String(r.detail??'')}</span>}</div>)}{!visible.length&&<p>Записей пока нет.</p>}</div></section>
  </div>
}
