import { useEffect, useMemo, useRef, useState } from 'react'
import { LoaderCircle, X } from 'lucide-react'
import type { ShipmentColumn } from './shipment-templates'
import type { ColumnFilter } from './shipment-filters'
import { monthName } from './utils'
export default function ShipmentColumnFilter({column,params,filter,onApply,onClose}:{column:ShipmentColumn;params:string;filter?:ColumnFilter;onApply:(filter?:ColumnFilter)=>void;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null),[values,setValues]=useState<string[]>([]),[selected,setSelected]=useState<string[]>(filter?.values??[]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[op,setOp]=useState<ColumnFilter['op']>(filter?.op??'values'),[value,setValue]=useState(filter?.value??''),[to,setTo]=useState(filter?.to??''),[retry,setRetry]=useState(0)
  useEffect(()=>{const element=dialog.current,focused=document.activeElement as HTMLElement|null;element?.showModal();return()=>{element?.close();focused?.focus()}},[])
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch(`/api/shipments?${params}&limit=1&facet=${encodeURIComponent(column.key)}`,{signal:controller.signal}).then(async r=>{const result=await r.json();if(!r.ok)throw new Error(result.error);return result}).then(r=>{setValues(r.facetValues);setSelected(filter?.values??r.facetValues)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[params,column.key,filter,retry])
  const matches=useMemo(()=>values.filter(v=>`${v} ${column.key==='month'&&/^\d{4}-\d{2}$/.test(v)?monthName(v):''}`.toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru'))),[values,search,column.key])
  const apply=()=>{if(op==='values'){if(selected.length===values.length)onApply();else if(selected.length>1000)setError('Уточните выбор: не более 1000 значений. Можно использовать диапазон.');else onApply({op,values:selected})}else if(op==='range'&&!value&&!to)setError('Укажите хотя бы одну границу.');else onApply({op,value,to})}
  return <dialog ref={dialog} className="shipment-filter-dialog" aria-labelledby="column-filter-title" onCancel={e=>{e.preventDefault();onClose()}}><header><h2 id="column-filter-title">Фильтр: {column.title}</h2><button className="icon-button" onClick={onClose} aria-label="Закрыть фильтр"><X size={19}/></button></header><label className="shipment-field"><span>Условие</span><select aria-label="Условие фильтра" value={op} onChange={e=>{setError('');setOp(e.target.value as ColumnFilter['op'])}}><option value="values">Выбрать значения</option><option value="contains">Содержит</option><option value="equals">Равно</option>{['number','date'].includes(column.kind)&&<option value="range">Диапазон</option>}<option value="empty">Пустые</option><option value="notEmpty">Непустые</option></select></label>
    {op==='values'?loading?<p><LoaderCircle className="spin" size={17}/>Загружаем значения всех строк…</p>:<><input className="filter-search" aria-label="Поиск значений колонки" placeholder="Найти значение…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="filter-selection-actions"><button className="text-button" onClick={()=>setSelected(previous=>[...new Set([...previous,...matches])])}>Выбрать найденные</button><button className="text-button" onClick={()=>setSelected(previous=>previous.filter(v=>!matches.includes(v)))}>Снять найденные</button></div><div className="filter-values">{matches.slice(0,200).map(v=><label key={v}><input type="checkbox" checked={selected.includes(v)} onChange={e=>setSelected(previous=>e.target.checked?[...previous,v]:previous.filter(x=>x!==v))}/><span>{!v?'(Пустые)':column.key==='month'&&/^\d{4}-\d{2}$/.test(v)?monthName(v):v}</span></label>)}{matches.length>200&&<p>Показано 200 из {matches.length}. Уточните поиск.</p>}</div><small>Выбрано {selected.length} из {values.length}</small></>:['contains','equals','range'].includes(op)&&<div className="filter-range"><label className="shipment-field"><span>{op==='range'?'От':'Значение'}</span><input aria-label={op==='range'?'От':'Значение фильтра'} type={column.kind==='date'?'date':'text'} inputMode={column.kind==='number'?'decimal':undefined} value={value} onChange={e=>{setError('');setValue(e.target.value)}}/></label>{op==='range'&&<label className="shipment-field"><span>До</span><input aria-label="До" type={column.kind==='date'?'date':'text'} value={to} onChange={e=>{setError('');setTo(e.target.value)}}/></label>}</div>}
    {error&&<div role="alert" className="shipment-error-text">{error}<button className="text-button" onClick={()=>setRetry(r=>r+1)}>Повторить</button></div>}<footer><button className="button" onClick={()=>onApply()}>Сбросить</button><button className="button primary" disabled={loading} onClick={apply}>Применить</button></footer></dialog>
}
